name: Pull request message

on:
  pull_request:
    types:
      - opened

permissions:
  pull-requests: write

jobs:
  build:
    name: Post message
    runs-on: ubuntu-latest
    steps:
      - run: gh pr comment $PR_URL --body "Thanks for opening this PR! Before anything, please check that the website builds correctly and that there is a minimal amount of typos. Thanks!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
